<?php

declare(strict_types=1);

/**
 * This file is part of the Webware Smf Legacy Router package.
 *
 * Copyright (c) 2026 Joey (aka Tyrsson) Smith <jsmith@webinertia.net>
 * and contributors.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace WebwareTest\Router;

use Mezzio\Router\Route;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use Psr\Http\Server\MiddlewareInterface;
use Webware\Router\QueryParamRoute;

#[CoversClass(QueryParamRoute::class)]
class QueryParamRouteTest extends TestCase
{
    private MiddlewareInterface $middleware;

    protected function setUp(): void
    {
        $this->middleware = $this->createMock(MiddlewareInterface::class);
    }

    public function testConstructorAcceptsQueryParamKeys(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type']
        );

        $this->assertInstanceOf(Route::class, $route);
        $this->assertSame(['action', 'type'], $route->getQueryParamKeys());
    }

    public function testAutoGeneratedNameIncludesQueryParamKeys(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type']
        );

        $this->assertSame('/api?action&type', $route->getName());
    }

    public function testAutoGeneratedNameWithSingleQueryParam(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action']
        );

        $this->assertSame('/api?action', $route->getName());
    }

    public function testAutoGeneratedNameWithoutQueryParams(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            []
        );

        $this->assertSame('/api', $route->getName());
    }

    public function testAutoGeneratedNameWithHttpMethod(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action'],
            ['GET', 'POST']
        );

        $this->assertSame('/api?action^GET:POST', $route->getName());
    }

    public function testAutoGeneratedNameWithHttpMethodAndMultipleQueryParams(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type'],
            ['GET']
        );

        $this->assertSame('/api?action&type^GET', $route->getName());
    }

    public function testExplicitNameIsPreserved(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type'],
            null,
            'custom-route'
        );

        $this->assertSame('custom-route', $route->getName());
    }

    public function testMatchesQueryParamsWithExactKeys(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type']
        );

        $this->assertTrue($route->matchesQueryParams(['action' => 'create', 'type' => 'user']));
    }

    public function testMatchesQueryParamsWithExtraKeys(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action']
        );

        // Extra keys are allowed, only required keys must be present
        $this->assertTrue($route->matchesQueryParams(['action' => 'create', 'extra' => 'value']));
    }

    public function testDoesNotMatchWhenRequiredKeyMissing(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type']
        );

        $this->assertFalse($route->matchesQueryParams(['action' => 'create']));
    }

    public function testMatchesQueryParamsIsCaseSensitive(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['Action']
        );

        $this->assertFalse($route->matchesQueryParams(['action' => 'create']));
        $this->assertTrue($route->matchesQueryParams(['Action' => 'create']));
    }

    public function testMatchesEmptyQueryParamsWhenNoKeysRequired(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            []
        );

        $this->assertTrue($route->matchesQueryParams([]));
        $this->assertTrue($route->matchesQueryParams(['any' => 'param']));
    }

    public function testQueryParamKeysStoredInOptions(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type']
        );

        $options = $route->getOptions();
        $this->assertArrayHasKey('query_params', $options);
        $this->assertSame(['action', 'type'], $options['query_params']);
    }

    public function testInheritsHttpMethodBehavior(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action'],
            ['GET', 'POST']
        );

        $this->assertTrue($route->allowsMethod('GET'));
        $this->assertTrue($route->allowsMethod('POST'));
        $this->assertFalse($route->allowsMethod('DELETE'));
        $this->assertFalse($route->allowsAnyMethod());
    }

    public function testAllowsAnyMethodWhenNotSpecified(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action']
        );

        $this->assertTrue($route->allowsAnyMethod());
        $this->assertTrue($route->allowsMethod('GET'));
        $this->assertTrue($route->allowsMethod('POST'));
        $this->assertTrue($route->allowsMethod('DELETE'));
    }
}
