<?php

declare(strict_types=1);

/**
 * This file is part of the Webware Smf Legacy Router package.
 *
 * Copyright (c) 2026 Joey (aka Tyrsson) Smith <jsmith@webinertia.net>
 * and contributors.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace WebwareTest\Router;

use Mezzio\Router\Route;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use Psr\Http\Server\MiddlewareInterface;
use Webware\Router\QueryParamRoute;

#[CoversClass(QueryParamRoute::class)]
class QueryParamRouteTest extends TestCase
{
    private MiddlewareInterface $middleware;

    protected function setUp(): void
    {
        $this->middleware = $this->createMock(MiddlewareInterface::class);
    }

    public function testConstructorAcceptsQueryParamKeys(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type']
        );

        $this->assertInstanceOf(Route::class, $route);
        $this->assertSame(['action', 'type'], $route->getQueryParamKeys());
    }

    public function testAutoGeneratedNameIncludesQueryParamKeys(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type']
        );

        $this->assertSame('/api?action&type', $route->getName());
    }

    public function testAutoGeneratedNameWithSingleQueryParam(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action']
        );

        $this->assertSame('/api?action', $route->getName());
    }

    public function testAutoGeneratedNameWithoutQueryParams(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            []
        );

        $this->assertSame('/api', $route->getName());
    }

    public function testAutoGeneratedNameWithHttpMethod(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action'],
            ['GET', 'POST']
        );

        $this->assertSame('/api?action^GET:POST', $route->getName());
    }

    public function testAutoGeneratedNameWithHttpMethodAndMultipleQueryParams(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type'],
            ['GET']
        );

        $this->assertSame('/api?action&type^GET', $route->getName());
    }

    public function testExplicitNameIsPreserved(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type'],
            null,
            'custom-route'
        );

        $this->assertSame('custom-route', $route->getName());
    }

    public function testMatchesQueryParamsWithExactKeys(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type']
        );

        $this->assertTrue($route->matchesQueryParams(['action' => 'create', 'type' => 'user']));
    }

    public function testMatchesQueryParamsWithExtraKeys(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action']
        );

        // Extra keys are allowed, only required keys must be present
        $this->assertTrue($route->matchesQueryParams(['action' => 'create', 'extra' => 'value']));
    }

    public function testDoesNotMatchWhenRequiredKeyMissing(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type']
        );

        $this->assertFalse($route->matchesQueryParams(['action' => 'create']));
    }

    public function testMatchesQueryParamsIsCaseSensitive(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['Action']
        );

        $this->assertFalse($route->matchesQueryParams(['action' => 'create']));
        $this->assertTrue($route->matchesQueryParams(['Action' => 'create']));
    }

    public function testMatchesEmptyQueryParamsWhenNoKeysRequired(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            []
        );

        $this->assertTrue($route->matchesQueryParams([]));
        $this->assertTrue($route->matchesQueryParams(['any' => 'param']));
    }

    public function testQueryParamKeysStoredInOptions(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'type']
        );

        $options = $route->getOptions();
        $this->assertArrayHasKey('query_params', $options);
        // Indexed arrays are normalized to associative with null values
        $this->assertSame(['action' => null, 'type' => null], $options['query_params']);
    }

    public function testInheritsHttpMethodBehavior(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action'],
            ['GET', 'POST']
        );

        $this->assertTrue($route->allowsMethod('GET'));
        $this->assertTrue($route->allowsMethod('POST'));
        $this->assertFalse($route->allowsMethod('DELETE'));
        $this->assertFalse($route->allowsAnyMethod());
    }

    public function testAllowsAnyMethodWhenNotSpecified(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action']
        );

        $this->assertTrue($route->allowsAnyMethod());
        $this->assertTrue($route->allowsMethod('GET'));
        $this->assertTrue($route->allowsMethod('POST'));
        $this->assertTrue($route->allowsMethod('DELETE'));
    }

    // Value matching tests

    public function testMatchesQueryParamsWithSpecificValue(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action' => 'profile', 'u' => null]
        );

        // Should match when action=profile and u has any value
        $this->assertTrue($route->matchesQueryParams(['action' => 'profile', 'u' => '1']));
        $this->assertTrue($route->matchesQueryParams(['action' => 'profile', 'u' => '123']));
        
        // Should NOT match when action has different value
        $this->assertFalse($route->matchesQueryParams(['action' => 'edit', 'u' => '1']));
    }

    public function testMatchesQueryParamsWithAllSpecificValues(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action' => 'profile', 'section' => 'settings']
        );

        // Should match only when both values match
        $this->assertTrue($route->matchesQueryParams(['action' => 'profile', 'section' => 'settings']));
        $this->assertFalse($route->matchesQueryParams(['action' => 'profile', 'section' => 'other']));
        $this->assertFalse($route->matchesQueryParams(['action' => 'other', 'section' => 'settings']));
    }

    public function testGetQueryParamConstraints(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action' => 'profile', 'u' => null]
        );

        $constraints = $route->getQueryParamConstraints();
        $this->assertSame(['action' => 'profile', 'u' => null], $constraints);
    }

    public function testBackwardCompatibilityWithIndexedArray(): void
    {
        // Old format: indexed array of keys
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action', 'u']
        );

        // Should be normalized to constraints with null values
        $this->assertSame(['action' => null, 'u' => null], $route->getQueryParamConstraints());
        $this->assertSame(['action', 'u'], $route->getQueryParamKeys());

        // Should match any values
        $this->assertTrue($route->matchesQueryParams(['action' => 'profile', 'u' => '1']));
        $this->assertTrue($route->matchesQueryParams(['action' => 'edit', 'u' => '2']));
    }

    public function testAutoGeneratedNameIncludesValueConstraints(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action' => 'profile', 'u' => null]
        );

        // Name should show value constraint for action but not u
        $this->assertSame('/api?action=profile&u', $route->getName());
    }

    public function testConstraintsStoredInOptions(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['action' => 'profile', 'u' => null]
        );

        $options = $route->getOptions();
        $this->assertArrayHasKey('query_params', $options);
        $this->assertSame(['action' => 'profile', 'u' => null], $options['query_params']);
    }

    public function testValueConstraintWithNumericValue(): void
    {
        $route = new QueryParamRoute(
            '/api',
            $this->middleware,
            ['page' => '1', 'limit' => null]
        );

        // String '1' should match string '1' exactly
        $this->assertTrue($route->matchesQueryParams(['page' => '1', 'limit' => '10']));
        $this->assertFalse($route->matchesQueryParams(['page' => '2', 'limit' => '10']));
        
        // Strict comparison - string '1' does not equal int 1
        $this->assertFalse($route->matchesQueryParams(['page' => 1, 'limit' => '10']));
    }
}
